---
- name: Debug ntp.yml variables
  ansible.builtin.debug:
    var: "{{ item }}"
  loop:
    - role_nutanix_prism_ntp_list
    - role_nutanix_prism_ntp_current_config.json | default('')
    - role_nutanix_prism_ntp_remove_entry.results | default('')
    - role_nutanix_prism_ntp_add_entry.results | default('')
