---
# tasks file for nutanix_role_nutanix_ntp
- name: Get current NTP configuration
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/cluster/ntp_servers"
    method: GET
    validate_certs: "{{ role_nutanix_prism_ntp_host_validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
  register: role_nutanix_prism_ntp_current_config

- name: Debug role_nutanix_prism_ntp_current_config
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_ntp_current_config }}"
  when: role_nutanix_prism_ntp_debug

- name: Remove configured NTP server if not provided
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/cluster/ntp_servers/{{ item }}"
    method: DELETE
    validate_certs: "{{ role_nutanix_prism_ntp_host_validate_certs }}"
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
    status_code: 204
  when:
    - item not in role_nutanix_prism_ntp_list
  register: role_nutanix_prism_ntp_remove_entry
  loop: "{{ role_nutanix_prism_ntp_current_config.json }}"

- name: Debug role_nutanix_prism_ntp_remove_entry
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_ntp_remove_entry }}"
  when: role_nutanix_prism_ntp_debug

- name: Add NTP server
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/cluster/ntp_servers"
    method: POST
    validate_certs: "{{ role_nutanix_prism_ntp_host_validate_certs }}"
    body:
      value: "{{ item }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
    status_code: 200,201
  register: role_nutanix_prism_ntp_add_entry
  loop: "{{ role_nutanix_prism_ntp_list }}"
  when: item not in role_nutanix_prism_ntp_current_config.json

- name: Debug role_nutanix_prism_ntp_add_entry
  ansible.builtin.debug:
    msg: "{{ role_nutanix_prism_ntp_add_entry }}"
  when: role_nutanix_prism_ntp_debug
